DROP TABLE IF EXISTS User;

CREATE TABLE User (
  USER_ID VARCHAR(250) PRIMARY KEY,
  password VARCHAR(250) NOT NULL, 
  role VARCHAR(250) DEFAULT NULL
  
);

DROP TABLE IF EXISTS User_Detail;

CREATE TABLE User_Detail (
  USER_DETAIL_ID INT PRIMARY KEY,
  USER_ID VARCHAR(250) NOT NULL,
  fname VARCHAR(250) NOT NULL,
  lname VARCHAR(250) NOT NULL,
  addressl1 VARCHAR(250) DEFAULT NULL,
  addressl2 VARCHAR(250) DEFAULT NULL,
  city VARCHAR(250) DEFAULT NULL,
  state VARCHAR(250) DEFAULT NULL,
  zip INT DEFAULT NULL,
  contact INT DEFAULT NULL  ,
  email VARCHAR(250) NOT NULL,
  foreign key (USER_ID) references User(USER_ID)
);

DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS (
  ORDER_ID INT PRIMARY KEY,
  user_id VARCHAR(250) NOT NULL,
  order_date date,
  status VARCHAR(250) DEFAULT NULL,
  total_amount INT NOT NULL,
  tax INT NOT NULL
);

DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
  PRODUCT_ID INT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  company VARCHAR(250) NOT NULL,
  price VARCHAR(250) DEFAULT NULL,
  quantity INT DEFAULT NULL
);

DROP TABLE IF EXISTS ORDER_DETAIL;

CREATE TABLE ORDER_DETAIL (
  ORDER_DETAIL_ID INT PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  amount INT NOT NULL,
  foreign key (order_id) references ORDERS(ORDER_ID)
);