DROP TABLE IF EXISTS User;

CREATE TABLE User (
  id VARCHAR(250) PRIMARY KEY,
  pass VARCHAR(250) NOT NULL,
  role VARCHAR(250) DEFAULT NULL
  
);

DROP TABLE IF EXISTS billionaires;

CREATE TABLE User_Details (
  id VARCHAR(250) PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  address_line1 VARCHAR(250) DEFAULT NULL,
  address_line2 VARCHAR(250) DEFAULT NULL,
  city VARCHAR(250) DEFAULT NULL,
  state VARCHAR(250) DEFAULT NULL,
  zip INT DEFAULT NULL,
  contact INT DEFAULT NULL  
);