DROP TABLE IF EXISTS User;

CREATE TABLE User (
  id VARCHAR(250) PRIMARY KEY,
  password VARCHAR(250) NOT NULL, 
  role VARCHAR(250) DEFAULT NULL
  
);

DROP TABLE IF EXISTS User_Detail;

CREATE TABLE User_Detail (
  id VARCHAR(250) PRIMARY KEY,
  fname VARCHAR(250) NOT NULL,
  lname VARCHAR(250) NOT NULL,
  addressl1 VARCHAR(250) DEFAULT NULL,
  addressl2 VARCHAR(250) DEFAULT NULL,
  city VARCHAR(250) DEFAULT NULL,
  state VARCHAR(250) DEFAULT NULL,
  zip INT DEFAULT NULL,
  contact INT DEFAULT NULL  ,
  email VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS (
  id INT PRIMARY KEY,
  user_id VARCHAR(250) NOT NULL,
  order_date date NOT NULL,
  status VARCHAR(250) DEFAULT NULL,
  total_amount INT NOT NULL,
  tax INT NOT NULL
);

DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
  id INT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  company VARCHAR(250) NOT NULL,
  price VARCHAR(250) DEFAULT NULL,
  quantity INT DEFAULT NULL
);

DROP TABLE IF EXISTS ORDER_DETAIL;

CREATE TABLE ORDER_DETAIL (
  id INT PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  amount INT NOT NULL
);